modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory (26 is current forge version)

[[mods]] #mandatory

modId="wtas" #mandatory

version="0.1.0" #mandatory

displayName="WackyToolsAndSuch" #mandatory

credits="Harry Talks for making a server hopefully with this mod on it" #optional

authors="Thermionic" #optional

description='''

Wacky Tools And Such is a mod about wacky tools and such there is not much else to say..

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wtas]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
